### ISSUE TITLE
Failed to reformat table

### ISSUE THREAD

**Issue by benblamey** [dbrockman/reformat-markdown-table#1]
```
$ pbpaste | reformat-markdown-table | pbcopy
/Users/benblamey/.nvm/versions/node/v4.2.4/lib/node_modules/reformat-markdown-table/lib/reformat-table.js:14
  table[1] = table[1].map(function(cell) {
                     ^

TypeError: Cannot read property 'map' of undefined
    at reformat (/Users/benblamey/.nvm/versions/node/v4.2.4/lib/node_modules/reformat-markdown-table/lib/reformat-table.js:14:22)
    at Socket.<anonymous> (/Users/benblamey/.nvm/versions/node/v4.2.4/lib/node_modules/reformat-markdown-table/bin/reformat-markdown-table:21:16)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by dbrockman** [comment]
:astonished:

**Comment by benblamey** [comment]
ahhh, tried it again and its worked....

**Comment by dbrockman** [comment]
It's not very user-friendly.
